#Creating First Dockerfile
# This is my first Docker image
#The Docker image will be based on the Ubuntu parent image.
FROM ubuntu
LABEL maintainer=sathsara@mydomain.com
RUN apt-get update
# parameters of container
CMD ["The Docker Workshop"]
# default excutable
ENTRYPOINT ["echo", "You are reading"]

# step of building image using dockerfile
# docker image build
# docker image list
# docker image build -t <repo>:<tag> .
# docker container run welcome:1.0

step 1: build dockerfile
step 2: build docker image
step 3: run container